# Generated by Django 4.2.6 on 2024-01-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментрі',
            },
        ),
        migrations.AddField(
            model_name='doormodel',
            name='Model_price',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
