# Generated by Django 4.2.6 on 2024-01-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doormodel',
            old_name='model_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='doormodel',
            old_name='model_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='doormodel',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doormodel',
            old_name='Model_price',
            new_name='price',
        ),
    ]
